import { PrismaClient, BusinessCategory, SubscriptionPlan } from '@prisma/client'

const prisma = new PrismaClient()

export const businessTypes = [
  {
    typeKey: 'coffee_shop_takeaway',
    name: 'Coffee Shop (Takeaway)',
    displayName: 'Coffee Shop - Takeaway Only',
    description: 'Perfect for coffee shops focused on grab-and-go service with quick checkout and loyalty programs',
    category: 'BEVERAGE' as BusinessCategory,
    subcategory: 'Coffee',
    hasDineIn: false,
    hasTakeaway: true,
    hasDelivery: false,
    hasKitchen: false,
    requiresTable: false,
    typicalOrderTime: 3,
    icon: 'Coffee',
    color: '#8B4513',
    isPopular: true,
    recommendedPlan: 'BASIC' as SubscriptionPlan,
    expectedDailyOrders: 200,
    tags: ['fast-service', 'beverages', 'loyalty'],
    sortOrder: 1,
    features: [
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_quick_checkout', isRecommended: true, isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_order_modifiers', isRecommended: true },
      { featureKey: 'enable_customer_database', isRecommended: true },
      { featureKey: 'enable_loyalty_program', isRecommended: true },
      { featureKey: 'enable_inventory_tracking', isRecommended: true },
      { featureKey: 'enable_low_stock_alerts', isRecommended: true },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_digital_wallet', isRecommended: true },
      { featureKey: 'enable_basic_reports', isRecommended: true },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
  {
    typeKey: 'kebab_shop_takeaway',
    name: 'Kebab Shop (Takeaway & Delivery)',
    displayName: 'Kebab/Fast Food Takeaway',
    description: 'Fast food takeaway with delivery service, kitchen display, and order customization',
    category: 'FOOD_SERVICE' as BusinessCategory,
    subcategory: 'Quick Service',
    hasDineIn: false,
    hasTakeaway: true,
    hasDelivery: true,
    hasKitchen: true,
    requiresTable: false,
    typicalOrderTime: 15,
    icon: 'Utensils',
    color: '#FF6347',
    isPopular: true,
    recommendedPlan: 'BASIC' as SubscriptionPlan,
    expectedDailyOrders: 150,
    tags: ['fast-food', 'delivery', 'kitchen'],
    sortOrder: 2,
    features: [
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_kitchen_display', isRecommended: true },
      { featureKey: 'enable_order_modifiers', isRecommended: true },
      { featureKey: 'enable_order_notes', isRecommended: true },
      { featureKey: 'enable_inventory_tracking', isRecommended: true },
      { featureKey: 'enable_low_stock_alerts', isRecommended: true },
      { featureKey: 'enable_customer_database', isRecommended: true },
      { featureKey: 'enable_delivery_management', isRecommended: true },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_basic_reports', isRecommended: true },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
  {
    typeKey: 'restaurant_full_service',
    name: 'Full-Service Restaurant',
    displayName: 'Full-Service Dine-In Restaurant',
    description: 'Traditional restaurant with table service, full menu, kitchen operations, and staff management',
    category: 'FOOD_SERVICE' as BusinessCategory,
    subcategory: 'Casual Dining',
    hasDineIn: true,
    hasTakeaway: true,
    hasDelivery: false,
    hasKitchen: true,
    requiresTable: true,
    typicalOrderTime: 30,
    icon: 'ChefHat',
    color: '#4169E1',
    isPopular: true,
    recommendedPlan: 'PRO' as SubscriptionPlan,
    expectedDailyOrders: 100,
    tags: ['full-service', 'tables', 'kitchen', 'staff'],
    sortOrder: 3,
    features: [
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_table_management', isRequired: true },
      { featureKey: 'enable_kitchen_display', isRecommended: true },
      { featureKey: 'enable_order_modifiers', isRecommended: true },
      { featureKey: 'enable_order_notes', isRecommended: true },
      { featureKey: 'enable_split_payments', isRecommended: true },
      { featureKey: 'enable_tipping', isRecommended: true },
      { featureKey: 'enable_inventory_tracking', isRecommended: true },
      { featureKey: 'enable_customer_database', isRecommended: true },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_table_reservations' },
      { featureKey: 'enable_waitlist' },
      { featureKey: 'enable_course_management' },
      { featureKey: 'enable_floor_plan' },
      { featureKey: 'enable_manual_discounts' },
      { featureKey: 'enable_auto_gratuity' },
      { featureKey: 'enable_shift_management' },
      { featureKey: 'enable_time_clock' },
      { featureKey: 'enable_tip_pooling' },
      { featureKey: 'enable_kitchen_printer' },
      { featureKey: 'enable_prep_stations' },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_basic_reports', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
  {
    typeKey: 'pizza_takeaway_delivery',
    name: 'Pizza Takeaway & Delivery',
    displayName: 'Pizza Shop - Takeaway & Delivery',
    description: 'Pizza restaurant focused on takeaway and delivery with online ordering and delivery zones',
    category: 'FOOD_SERVICE' as BusinessCategory,
    subcategory: 'Pizza',
    hasDineIn: false,
    hasTakeaway: true,
    hasDelivery: true,
    hasKitchen: true,
    requiresTable: false,
    typicalOrderTime: 25,
    icon: 'Pizza',
    color: '#FF4500',
    isPopular: true,
    recommendedPlan: 'PRO' as SubscriptionPlan,
    expectedDailyOrders: 120,
    tags: ['pizza', 'delivery', 'online-ordering'],
    sortOrder: 4,
    features: [
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_kitchen_display', isRecommended: true },
      { featureKey: 'enable_order_modifiers', isRecommended: true },
      { featureKey: 'enable_order_notes', isRecommended: true },
      { featureKey: 'enable_customer_database', isRecommended: true },
      { featureKey: 'enable_online_ordering', isRecommended: true },
      { featureKey: 'enable_delivery_management', isRecommended: true },
      { featureKey: 'enable_delivery_zones', isRecommended: true },
      { featureKey: 'enable_order_scheduling', isRecommended: true },
      { featureKey: 'enable_combo_meals' },
      { featureKey: 'enable_inventory_tracking' },
      { featureKey: 'enable_coupon_codes' },
      { featureKey: 'enable_loyalty_program' },
      { featureKey: 'enable_manual_discounts' },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_basic_reports', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
  {
    typeKey: 'bakery',
    name: 'Bakery',
    displayName: 'Bakery / Pastry Shop',
    description: 'Bakery with fresh daily products, batch tracking, and waste management',
    category: 'FOOD_SERVICE' as BusinessCategory,
    subcategory: 'Bakery',
    hasDineIn: false,
    hasTakeaway: true,
    hasDelivery: false,
    hasKitchen: false,
    requiresTable: false,
    typicalOrderTime: 5,
    icon: 'Croissant',
    color: '#DEB887',
    isPopular: false,
    recommendedPlan: 'BASIC' as SubscriptionPlan,
    expectedDailyOrders: 100,
    tags: ['bakery', 'fresh', 'daily'],
    sortOrder: 5,
    features: [
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_quick_checkout', isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_inventory_tracking', isRecommended: true },
      { featureKey: 'enable_low_stock_alerts', isRecommended: true },
      { featureKey: 'enable_batch_expiry', isRecommended: true },
      { featureKey: 'enable_waste_tracking', isRecommended: true },
      { featureKey: 'enable_customer_database' },
      { featureKey: 'enable_loyalty_program' },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_basic_reports', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
  {
    typeKey: 'bar_pub',
    name: 'Bar / Pub',
    displayName: 'Bar or Pub',
    description: 'Bar with drinks and light food, quick service, and tab management',
    category: 'HOSPITALITY' as BusinessCategory,
    subcategory: 'Bar',
    hasDineIn: true,
    hasTakeaway: false,
    hasDelivery: false,
    hasKitchen: false,
    requiresTable: true,
    typicalOrderTime: 5,
    icon: 'Beer',
    color: '#FFD700',
    isPopular: false,
    recommendedPlan: 'PRO' as SubscriptionPlan,
    expectedDailyOrders: 200,
    tags: ['bar', 'drinks', 'quick-service'],
    sortOrder: 6,
    features: [
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_table_management', isRequired: true },
      { featureKey: 'enable_quick_checkout', isRecommended: true },
      { featureKey: 'enable_inventory_tracking', isRecommended: true },
      { featureKey: 'enable_low_stock_alerts', isRecommended: true },
      { featureKey: 'enable_tipping', isRecommended: true },
      { featureKey: 'enable_split_payments', isRecommended: true },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_happy_hour' },
      { featureKey: 'enable_order_modifiers' },
      { featureKey: 'enable_manual_discounts' },
      { featureKey: 'enable_shift_management' },
      { featureKey: 'enable_time_clock' },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_basic_reports', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
  {
    typeKey: 'retail_store',
    name: 'Retail Store',
    displayName: 'Retail / Convenience Store',
    description: 'General retail with barcode scanning, supplier management, and detailed inventory',
    category: 'RETAIL' as BusinessCategory,
    subcategory: 'General',
    hasDineIn: false,
    hasTakeaway: false,
    hasDelivery: false,
    hasKitchen: false,
    requiresTable: false,
    typicalOrderTime: 5,
    icon: 'Store',
    color: '#32CD32',
    isPopular: false,
    recommendedPlan: 'PRO' as SubscriptionPlan,
    expectedDailyOrders: 150,
    tags: ['retail', 'barcode', 'inventory'],
    sortOrder: 7,
    features: [
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_barcode_scanning', isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_inventory_tracking', isRecommended: true },
      { featureKey: 'enable_low_stock_alerts', isRecommended: true },
      { featureKey: 'enable_supplier_management', isRecommended: true },
      { featureKey: 'enable_purchase_orders', isRecommended: true },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_customer_database' },
      { featureKey: 'enable_loyalty_program' },
      { featureKey: 'enable_manual_discounts' },
      { featureKey: 'enable_coupon_codes' },
      { featureKey: 'enable_gift_cards' },
      { featureKey: 'enable_shift_management' },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_basic_reports', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
  {
    typeKey: 'food_truck',
    name: 'Food Truck',
    displayName: 'Food Truck / Mobile Food',
    description: 'Mobile food service with quick checkout and limited inventory tracking',
    category: 'FOOD_SERVICE' as BusinessCategory,
    subcategory: 'Mobile',
    hasDineIn: false,
    hasTakeaway: true,
    hasDelivery: false,
    hasKitchen: true,
    requiresTable: false,
    typicalOrderTime: 10,
    icon: 'Truck',
    color: '#FF8C00',
    isPopular: false,
    recommendedPlan: 'BASIC' as SubscriptionPlan,
    expectedDailyOrders: 80,
    tags: ['mobile', 'quick-service', 'limited-inventory'],
    sortOrder: 8,
    features: [
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_quick_checkout', isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_kitchen_display', isRecommended: true },
      { featureKey: 'enable_order_modifiers', isRecommended: true },
      { featureKey: 'enable_order_notes', isRecommended: true },
      { featureKey: 'enable_inventory_tracking', isRecommended: true },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_digital_wallet', isRecommended: true },
      { featureKey: 'enable_customer_database' },
      { featureKey: 'enable_loyalty_program' },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_basic_reports', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
  {
    typeKey: 'restaurant_chain',
    name: 'Multi-Location Restaurant Chain',
    displayName: 'Restaurant Chain (Multiple Locations)',
    description: 'Restaurant with 3+ locations requiring centralized management, transfers, and consolidated reporting',
    category: 'FOOD_SERVICE' as BusinessCategory,
    subcategory: 'Chain',
    hasDineIn: true,
    hasTakeaway: true,
    hasDelivery: true,
    hasKitchen: true,
    requiresTable: true,
    typicalOrderTime: 20,
    icon: 'Building2',
    color: '#8B008B',
    isPopular: false,
    recommendedPlan: 'ENTERPRISE' as SubscriptionPlan,
    expectedDailyOrders: 500,
    tags: ['chain', 'multi-location', 'enterprise'],
    sortOrder: 9,
    features: [
      // Core (All required/recommended)
      { featureKey: 'enable_pos_interface', isRequired: true },
      { featureKey: 'enable_order_history', isRequired: true },
      { featureKey: 'enable_multi_location', isRequired: true },
      { featureKey: 'enable_table_management', isRecommended: true },
      { featureKey: 'enable_kitchen_display', isRecommended: true },
      { featureKey: 'enable_order_modifiers', isRecommended: true },
      { featureKey: 'enable_inventory_tracking', isRecommended: true },
      { featureKey: 'enable_location_transfers', isRecommended: true },
      { featureKey: 'enable_consolidated_reports', isRecommended: true },
      { featureKey: 'enable_centralized_menu', isRecommended: true },
      { featureKey: 'enable_supplier_management', isRecommended: true },
      { featureKey: 'enable_purchase_orders', isRecommended: true },
      { featureKey: 'enable_customer_database', isRecommended: true },
      { featureKey: 'enable_loyalty_program', isRecommended: true },
      { featureKey: 'enable_user_management', isRecommended: true },
      { featureKey: 'enable_staff_scheduling', isRecommended: true },
      { featureKey: 'enable_time_clock', isRecommended: true },
      { featureKey: 'enable_shift_management', isRecommended: true },
      { featureKey: 'enable_performance_tracking', isRecommended: true },
      { featureKey: 'enable_advanced_analytics', isRecommended: true },
      { featureKey: 'enable_sales_forecasting', isRecommended: true },
      { featureKey: 'enable_inventory_forecasting', isRecommended: true },
      { featureKey: 'enable_menu_engineering', isRecommended: true },
      // All optional features available
      { featureKey: 'enable_online_ordering' },
      { featureKey: 'enable_delivery_management' },
      { featureKey: 'enable_table_reservations' },
      { featureKey: 'enable_waitlist' },
      { featureKey: 'enable_course_management' },
      { featureKey: 'enable_tipping' },
      { featureKey: 'enable_split_payments' },
      { featureKey: 'enable_recipe_management' },
      { featureKey: 'enable_waste_tracking' },
      { featureKey: 'enable_email_marketing' },
      { featureKey: 'enable_sms_marketing' },
      { featureKey: 'enable_cash_payments', isRecommended: true },
      { featureKey: 'enable_card_payments', isRecommended: true },
      { featureKey: 'enable_audit_logs', isRequired: true },
    ],
  },
]

export async function seedBusinessTypes() {
  console.log('🌱 Seeding business type templates...')

  for (const businessType of businessTypes) {
    const { features, ...templateData } = businessType

    // Create or update template
    const template = await prisma.business_type_templates.upsert({
      where: { typeKey: businessType.typeKey },
      update: templateData,
      create: templateData,
    })

    // Link features to template
    for (const templateFeature of features) {
      const feature = await prisma.feature_catalog.findUnique({
        where: { featureKey: templateFeature.featureKey },
      })

      if (feature) {
        await prisma.template_features.upsert({
          where: {
            templateId_featureId: {
              templateId: template.id,
              featureId: feature.id,
            },
          },
          update: {
            isEnabledByDefault: true,
            isRecommended: templateFeature.isRecommended ?? false,
            isRequired: templateFeature.isRequired ?? false,
          },
          create: {
            templateId: template.id,
            featureId: feature.id,
            isEnabledByDefault: true,
            isRecommended: templateFeature.isRecommended ?? false,
            isRequired: templateFeature.isRequired ?? false,
          },
        })
      }
    }
  }

  console.log(`✅ Seeded ${businessTypes.length} business type templates`)
}
