import { PrismaClient, FeatureCategory, SubscriptionPlan } from '@prisma/client'

const prisma = new PrismaClient()

export const features = [
  // CORE_POS Features
  {
    featureKey: 'enable_pos_interface',
    name: 'Point of Sale Interface',
    description: 'Core POS with product selection and checkout',
    category: 'CORE_POS' as FeatureCategory,
    icon: 'ShoppingCart',
    isCore: true,
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 1,
  },
  {
    featureKey: 'enable_quick_checkout',
    name: 'Quick Checkout Mode',
    description: 'Fast checkout with minimal clicks for high-volume businesses',
    category: 'CORE_POS' as FeatureCategory,
    icon: 'Zap',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    dependsOn: ['enable_pos_interface'],
    sortOrder: 2,
  },
  {
    featureKey: 'enable_barcode_scanning',
    name: 'Barcode Scanning',
    description: 'Scan product barcodes for fast item entry',
    category: 'CORE_POS' as FeatureCategory,
    icon: 'Scan',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    dependsOn: ['enable_pos_interface'],
    sortOrder: 3,
  },

  // INVENTORY Features
  {
    featureKey: 'enable_inventory_tracking',
    name: 'Inventory Tracking',
    description: 'Track stock levels automatically on sales',
    category: 'INVENTORY' as FeatureCategory,
    icon: 'Package',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 10,
  },
  {
    featureKey: 'enable_low_stock_alerts',
    name: 'Low Stock Alerts',
    description: 'Get notified when products run low',
    category: 'INVENTORY' as FeatureCategory,
    icon: 'AlertTriangle',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    dependsOn: ['enable_inventory_tracking'],
    sortOrder: 11,
  },
  {
    featureKey: 'enable_supplier_management',
    name: 'Supplier Management',
    description: 'Manage suppliers, contacts, and pricing',
    category: 'INVENTORY' as FeatureCategory,
    icon: 'Truck',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 12,
  },
  {
    featureKey: 'enable_purchase_orders',
    name: 'Purchase Orders',
    description: 'Create and track purchase orders to suppliers',
    category: 'INVENTORY' as FeatureCategory,
    icon: 'FileText',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_supplier_management', 'enable_inventory_tracking'],
    sortOrder: 13,
  },
  {
    featureKey: 'enable_recipe_management',
    name: 'Recipe & Ingredient Tracking',
    description: 'Track ingredients used in each menu item',
    category: 'INVENTORY' as FeatureCategory,
    icon: 'BookOpen',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_inventory_tracking'],
    sortOrder: 14,
  },
  {
    featureKey: 'enable_waste_tracking',
    name: 'Waste Tracking',
    description: 'Record expired, damaged, or wasted inventory',
    category: 'INVENTORY' as FeatureCategory,
    icon: 'Trash2',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_inventory_tracking'],
    sortOrder: 15,
  },
  {
    featureKey: 'enable_batch_expiry',
    name: 'Batch & Expiry Tracking',
    description: 'Track batch numbers and expiration dates',
    category: 'INVENTORY' as FeatureCategory,
    icon: 'Calendar',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_inventory_tracking'],
    sortOrder: 16,
  },

  // ORDER_MANAGEMENT Features
  {
    featureKey: 'enable_order_history',
    name: 'Order History',
    description: 'View and search past orders',
    category: 'ORDER_MANAGEMENT' as FeatureCategory,
    icon: 'History',
    isCore: true,
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 20,
  },
  {
    featureKey: 'enable_order_notes',
    name: 'Order Notes',
    description: 'Add special instructions to orders',
    category: 'ORDER_MANAGEMENT' as FeatureCategory,
    icon: 'MessageSquare',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 21,
  },
  {
    featureKey: 'enable_order_modifiers',
    name: 'Product Modifiers',
    description: 'Customize products (size, extras, removals)',
    category: 'ORDER_MANAGEMENT' as FeatureCategory,
    icon: 'Sliders',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 22,
  },
  {
    featureKey: 'enable_combo_meals',
    name: 'Combo Meals & Bundles',
    description: 'Create meal deals and product bundles',
    category: 'ORDER_MANAGEMENT' as FeatureCategory,
    icon: 'Package',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 23,
  },
  {
    featureKey: 'enable_order_scheduling',
    name: 'Order Scheduling',
    description: 'Accept orders for future pickup/delivery',
    category: 'ORDER_MANAGEMENT' as FeatureCategory,
    icon: 'Clock',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 24,
  },

  // TABLE_MANAGEMENT Features
  {
    featureKey: 'enable_table_management',
    name: 'Table Management',
    description: 'Track table status and assignments',
    category: 'TABLE_MANAGEMENT' as FeatureCategory,
    icon: 'Grid3x3',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 30,
  },
  {
    featureKey: 'enable_floor_plan',
    name: 'Visual Floor Plan',
    description: 'Visual table layout and status',
    category: 'TABLE_MANAGEMENT' as FeatureCategory,
    icon: 'Map',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_table_management'],
    sortOrder: 31,
  },
  {
    featureKey: 'enable_table_reservations',
    name: 'Reservations',
    description: 'Accept and manage table reservations',
    category: 'TABLE_MANAGEMENT' as FeatureCategory,
    icon: 'CalendarCheck',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_table_management'],
    sortOrder: 32,
  },
  {
    featureKey: 'enable_waitlist',
    name: 'Waitlist Management',
    description: 'Manage walk-in customer queue',
    category: 'TABLE_MANAGEMENT' as FeatureCategory,
    icon: 'Users',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_table_management'],
    sortOrder: 33,
  },
  {
    featureKey: 'enable_table_qr_ordering',
    name: 'QR Code Table Ordering',
    description: 'Customers scan QR to order from table',
    category: 'TABLE_MANAGEMENT' as FeatureCategory,
    icon: 'QrCode',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_table_management'],
    sortOrder: 34,
  },

  // KITCHEN_OPERATIONS Features
  {
    featureKey: 'enable_kitchen_display',
    name: 'Kitchen Display System (KDS)',
    description: 'Real-time order display for kitchen staff',
    category: 'KITCHEN_OPERATIONS' as FeatureCategory,
    icon: 'Monitor',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 40,
  },
  {
    featureKey: 'enable_kitchen_printer',
    name: 'Kitchen Printer',
    description: 'Print orders directly to kitchen',
    category: 'KITCHEN_OPERATIONS' as FeatureCategory,
    icon: 'Printer',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 41,
  },
  {
    featureKey: 'enable_prep_stations',
    name: 'Prep Station Routing',
    description: 'Route orders to specific kitchen stations',
    category: 'KITCHEN_OPERATIONS' as FeatureCategory,
    icon: 'GitBranch',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_kitchen_display'],
    sortOrder: 42,
  },
  {
    featureKey: 'enable_course_management',
    name: 'Course Timing',
    description: 'Fire appetizers, hold entrees, course sequencing',
    category: 'KITCHEN_OPERATIONS' as FeatureCategory,
    icon: 'Timer',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_kitchen_display'],
    sortOrder: 43,
  },
  {
    featureKey: 'enable_prep_lists',
    name: 'Prep Lists',
    description: 'Generate prep lists for kitchen',
    category: 'KITCHEN_OPERATIONS' as FeatureCategory,
    icon: 'ClipboardList',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 44,
  },

  // CUSTOMER_MANAGEMENT Features
  {
    featureKey: 'enable_customer_database',
    name: 'Customer Database',
    description: 'Store customer information and history',
    category: 'CUSTOMER_MANAGEMENT' as FeatureCategory,
    icon: 'Users',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 50,
  },
  {
    featureKey: 'enable_loyalty_program',
    name: 'Loyalty Points',
    description: 'Earn and redeem loyalty points',
    category: 'CUSTOMER_MANAGEMENT' as FeatureCategory,
    icon: 'Award',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    dependsOn: ['enable_customer_database'],
    sortOrder: 51,
  },
  {
    featureKey: 'enable_customer_profiles',
    name: 'Customer Profiles',
    description: 'Detailed customer preferences and history',
    category: 'CUSTOMER_MANAGEMENT' as FeatureCategory,
    icon: 'UserCircle',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_customer_database'],
    sortOrder: 52,
  },
  {
    featureKey: 'enable_customer_analytics',
    name: 'Customer Analytics',
    description: 'RFM segmentation, churn prediction, LTV',
    category: 'CUSTOMER_MANAGEMENT' as FeatureCategory,
    icon: 'TrendingUp',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_customer_database'],
    sortOrder: 53,
  },
  {
    featureKey: 'enable_birthday_rewards',
    name: 'Birthday Rewards',
    description: 'Automatic birthday discounts and notifications',
    category: 'CUSTOMER_MANAGEMENT' as FeatureCategory,
    icon: 'Gift',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_customer_database', 'enable_loyalty_program'],
    sortOrder: 54,
  },

  // PAYMENT_PROCESSING Features
  {
    featureKey: 'enable_cash_payments',
    name: 'Cash Payments',
    description: 'Accept cash with change calculation',
    category: 'PAYMENT_PROCESSING' as FeatureCategory,
    icon: 'DollarSign',
    isCore: true,
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 60,
  },
  {
    featureKey: 'enable_card_payments',
    name: 'Card Payments',
    description: 'Accept credit/debit cards',
    category: 'PAYMENT_PROCESSING' as FeatureCategory,
    icon: 'CreditCard',
    isCore: true,
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 61,
  },
  {
    featureKey: 'enable_digital_wallet',
    name: 'Digital Wallets',
    description: 'Accept Apple Pay, Google Pay, etc.',
    category: 'PAYMENT_PROCESSING' as FeatureCategory,
    icon: 'Smartphone',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 62,
  },
  {
    featureKey: 'enable_split_payments',
    name: 'Split Payments',
    description: 'Split bill by person, amount, or item',
    category: 'PAYMENT_PROCESSING' as FeatureCategory,
    icon: 'Split',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 63,
  },
  {
    featureKey: 'enable_tipping',
    name: 'Tip Processing',
    description: 'Add tips to orders',
    category: 'PAYMENT_PROCESSING' as FeatureCategory,
    icon: 'Heart',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 64,
  },
  {
    featureKey: 'enable_tip_pooling',
    name: 'Tip Pooling',
    description: 'Distribute tips among staff',
    category: 'PAYMENT_PROCESSING' as FeatureCategory,
    icon: 'Users',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_tipping'],
    sortOrder: 65,
  },
  {
    featureKey: 'enable_auto_gratuity',
    name: 'Auto-Gratuity',
    description: 'Automatic gratuity for large parties',
    category: 'PAYMENT_PROCESSING' as FeatureCategory,
    icon: 'Percent',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_tipping'],
    sortOrder: 66,
  },
  {
    featureKey: 'enable_gift_cards',
    name: 'Gift Cards',
    description: 'Sell and redeem gift cards',
    category: 'PAYMENT_PROCESSING' as FeatureCategory,
    icon: 'Gift',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 67,
  },

  // DISCOUNTS_PROMOTIONS Features
  {
    featureKey: 'enable_manual_discounts',
    name: 'Manual Discounts',
    description: 'Apply percentage or fixed discounts',
    category: 'DISCOUNTS_PROMOTIONS' as FeatureCategory,
    icon: 'Tag',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 70,
  },
  {
    featureKey: 'enable_coupon_codes',
    name: 'Coupon Codes',
    description: 'Create and validate coupon codes',
    category: 'DISCOUNTS_PROMOTIONS' as FeatureCategory,
    icon: 'Ticket',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 71,
  },
  {
    featureKey: 'enable_happy_hour',
    name: 'Happy Hour Pricing',
    description: 'Time-based automatic discounts',
    category: 'DISCOUNTS_PROMOTIONS' as FeatureCategory,
    icon: 'Clock',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 72,
  },
  {
    featureKey: 'enable_buy_x_get_y',
    name: 'Buy X Get Y Deals',
    description: 'BOGO and quantity-based deals',
    category: 'DISCOUNTS_PROMOTIONS' as FeatureCategory,
    icon: 'ShoppingBag',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 73,
  },
  {
    featureKey: 'enable_loyalty_rewards',
    name: 'Loyalty Rewards Redemption',
    description: 'Redeem points for discounts/free items',
    category: 'DISCOUNTS_PROMOTIONS' as FeatureCategory,
    icon: 'Star',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_loyalty_program'],
    sortOrder: 74,
  },

  // STAFF_MANAGEMENT Features
  {
    featureKey: 'enable_user_management',
    name: 'User Management',
    description: 'Add/remove staff with roles',
    category: 'STAFF_MANAGEMENT' as FeatureCategory,
    icon: 'Users',
    isCore: true,
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 80,
  },
  {
    featureKey: 'enable_time_clock',
    name: 'Time Clock',
    description: 'Clock in/out and break tracking',
    category: 'STAFF_MANAGEMENT' as FeatureCategory,
    icon: 'Clock',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 81,
  },
  {
    featureKey: 'enable_shift_management',
    name: 'Shift Management',
    description: 'Open/close shifts with cash reconciliation',
    category: 'STAFF_MANAGEMENT' as FeatureCategory,
    icon: 'Calendar',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 82,
  },
  {
    featureKey: 'enable_staff_scheduling',
    name: 'Staff Scheduling',
    description: 'Weekly schedules and shift assignment',
    category: 'STAFF_MANAGEMENT' as FeatureCategory,
    icon: 'CalendarDays',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 83,
  },
  {
    featureKey: 'enable_performance_tracking',
    name: 'Performance Metrics',
    description: 'Track sales per employee',
    category: 'STAFF_MANAGEMENT' as FeatureCategory,
    icon: 'BarChart2',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 84,
  },
  {
    featureKey: 'enable_staff_permissions',
    name: 'Granular Permissions',
    description: 'Detailed permission control per user',
    category: 'STAFF_MANAGEMENT' as FeatureCategory,
    icon: 'Lock',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_user_management'],
    sortOrder: 85,
  },

  // MULTI_LOCATION Features
  {
    featureKey: 'enable_multi_location',
    name: 'Multi-Location Support',
    description: 'Manage multiple business locations',
    category: 'MULTI_LOCATION' as FeatureCategory,
    icon: 'Building',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 90,
  },
  {
    featureKey: 'enable_location_transfers',
    name: 'Inventory Transfers',
    description: 'Transfer stock between locations',
    category: 'MULTI_LOCATION' as FeatureCategory,
    icon: 'ArrowRightLeft',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_multi_location', 'enable_inventory_tracking'],
    sortOrder: 91,
  },
  {
    featureKey: 'enable_consolidated_reports',
    name: 'Consolidated Reporting',
    description: 'View reports across all locations',
    category: 'MULTI_LOCATION' as FeatureCategory,
    icon: 'PieChart',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_multi_location'],
    sortOrder: 92,
  },
  {
    featureKey: 'enable_centralized_menu',
    name: 'Centralized Menu Management',
    description: 'Manage menu across all locations',
    category: 'MULTI_LOCATION' as FeatureCategory,
    icon: 'BookOpen',
    minimumPlan: 'ENTERPRISE' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_multi_location'],
    sortOrder: 93,
  },

  // ONLINE_ORDERING Features
  {
    featureKey: 'enable_online_ordering',
    name: 'Online Ordering',
    description: 'Customer web/app ordering',
    category: 'ONLINE_ORDERING' as FeatureCategory,
    icon: 'Globe',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 100,
  },
  {
    featureKey: 'enable_delivery_management',
    name: 'Delivery Management',
    description: 'Manage own delivery drivers',
    category: 'DELIVERY_MANAGEMENT' as FeatureCategory,
    icon: 'Bike',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 110,
  },
  {
    featureKey: 'enable_third_party_delivery',
    name: 'Third-Party Delivery Integration',
    description: 'Integrate with UberEats, DoorDash, etc.',
    category: 'DELIVERY_MANAGEMENT' as FeatureCategory,
    icon: 'Truck',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 111,
  },
  {
    featureKey: 'enable_delivery_zones',
    name: 'Delivery Zones',
    description: 'Set delivery areas and fees',
    category: 'DELIVERY_MANAGEMENT' as FeatureCategory,
    icon: 'MapPin',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_delivery_management'],
    sortOrder: 112,
  },

  // MARKETING Features
  {
    featureKey: 'enable_email_marketing',
    name: 'Email Marketing',
    description: 'Send promotional emails to customers',
    category: 'MARKETING' as FeatureCategory,
    icon: 'Mail',
    minimumPlan: 'ENTERPRISE' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_customer_database'],
    sortOrder: 120,
  },
  {
    featureKey: 'enable_sms_marketing',
    name: 'SMS Marketing',
    description: 'Send SMS campaigns to customers',
    category: 'MARKETING' as FeatureCategory,
    icon: 'MessageSquare',
    minimumPlan: 'ENTERPRISE' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_customer_database'],
    sortOrder: 121,
  },
  {
    featureKey: 'enable_push_notifications',
    name: 'Push Notifications',
    description: 'Send app push notifications',
    category: 'MARKETING' as FeatureCategory,
    icon: 'Bell',
    minimumPlan: 'ENTERPRISE' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 122,
  },
  {
    featureKey: 'enable_referral_program',
    name: 'Referral Program',
    description: 'Customer referral rewards',
    category: 'MARKETING' as FeatureCategory,
    icon: 'UserPlus',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_customer_database'],
    sortOrder: 123,
  },

  // ANALYTICS_REPORTS Features
  {
    featureKey: 'enable_basic_reports',
    name: 'Basic Reports',
    description: 'Sales, orders, and inventory reports',
    category: 'ANALYTICS_REPORTS' as FeatureCategory,
    icon: 'BarChart',
    isCore: true,
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 130,
  },
  {
    featureKey: 'enable_advanced_analytics',
    name: 'Advanced Analytics',
    description: 'Detailed business intelligence',
    category: 'ANALYTICS_REPORTS' as FeatureCategory,
    icon: 'LineChart',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 131,
  },
  {
    featureKey: 'enable_sales_forecasting',
    name: 'Sales Forecasting',
    description: 'Predict future sales trends',
    category: 'ANALYTICS_REPORTS' as FeatureCategory,
    icon: 'TrendingUp',
    minimumPlan: 'ENTERPRISE' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 132,
  },
  {
    featureKey: 'enable_inventory_forecasting',
    name: 'Inventory Forecasting',
    description: 'Predict inventory needs',
    category: 'ANALYTICS_REPORTS' as FeatureCategory,
    icon: 'PackageSearch',
    minimumPlan: 'ENTERPRISE' as SubscriptionPlan,
    requiresUpgrade: true,
    dependsOn: ['enable_inventory_tracking'],
    sortOrder: 133,
  },
  {
    featureKey: 'enable_menu_engineering',
    name: 'Menu Engineering',
    description: 'Analyze product profitability',
    category: 'ANALYTICS_REPORTS' as FeatureCategory,
    icon: 'Target',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 134,
  },
  {
    featureKey: 'enable_custom_reports',
    name: 'Custom Reports',
    description: 'Build custom report templates',
    category: 'ANALYTICS_REPORTS' as FeatureCategory,
    icon: 'FileText',
    minimumPlan: 'ENTERPRISE' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 135,
  },

  // HARDWARE_INTEGRATION Features
  {
    featureKey: 'enable_thermal_printer',
    name: 'Thermal Printer',
    description: 'Print receipts to thermal printer',
    category: 'HARDWARE_INTEGRATION' as FeatureCategory,
    icon: 'Printer',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 140,
  },
  {
    featureKey: 'enable_cash_drawer',
    name: 'Cash Drawer',
    description: 'Automatic cash drawer control',
    category: 'HARDWARE_INTEGRATION' as FeatureCategory,
    icon: 'DollarSign',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 141,
  },
  {
    featureKey: 'enable_customer_display',
    name: 'Customer Display',
    description: 'Show items and total to customer',
    category: 'HARDWARE_INTEGRATION' as FeatureCategory,
    icon: 'Monitor',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 142,
  },
  {
    featureKey: 'enable_scale',
    name: 'Scale Integration',
    description: 'Weigh items sold by weight',
    category: 'HARDWARE_INTEGRATION' as FeatureCategory,
    icon: 'Scale',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 143,
  },

  // COMPLIANCE_SECURITY Features
  {
    featureKey: 'enable_audit_logs',
    name: 'Audit Logs',
    description: 'Track all system actions',
    category: 'COMPLIANCE_SECURITY' as FeatureCategory,
    icon: 'FileText',
    isCore: true,
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 150,
  },
  {
    featureKey: 'enable_void_approval',
    name: 'Void Approval',
    description: 'Require manager approval to void items',
    category: 'COMPLIANCE_SECURITY' as FeatureCategory,
    icon: 'Shield',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 151,
  },
  {
    featureKey: 'enable_refund_approval',
    name: 'Refund Approval',
    description: 'Require manager approval for refunds',
    category: 'COMPLIANCE_SECURITY' as FeatureCategory,
    icon: 'ShieldCheck',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 152,
  },
  {
    featureKey: 'enable_discount_approval',
    name: 'Discount Approval',
    description: 'Require approval for discounts over threshold',
    category: 'COMPLIANCE_SECURITY' as FeatureCategory,
    icon: 'ShieldAlert',
    minimumPlan: 'PRO' as SubscriptionPlan,
    requiresUpgrade: true,
    sortOrder: 153,
  },
  {
    featureKey: 'enable_cash_drawer_management',
    name: 'Cash Drawer Management',
    description: 'Track cash drawer open/close events',
    category: 'COMPLIANCE_SECURITY' as FeatureCategory,
    icon: 'Lock',
    minimumPlan: 'BASIC' as SubscriptionPlan,
    sortOrder: 154,
  },
]

export async function seedFeatures() {
  console.log('🌱 Seeding feature catalog...')

  for (const feature of features) {
    await prisma.feature_catalog.upsert({
      where: { featureKey: feature.featureKey },
      update: feature,
      create: feature,
    })
  }

  console.log(`✅ Seeded ${features.length} features`)
}
